### ISSUE TITLE
Multiple Id's per badge: Palimpsest Method

### ISSUE THREAD

**Issue by cmcavoy** [openbadges/openbadges-discussion#19]
# Multiple Identities Per Badge, Palimpsest Proposal
## The Problem

When you're issued a badge, a single identity, usually an email, is the only identity you're allowed to associate with a badge.
## Proposed Solution

Extend the assertion specification to allow multiple identities per badge.
## The problems created by the solution

Presumably, an issuing organization will only know one identity for the earner of the badge. They'll issue to that identity, maybe signing the badge. The signature will be based on a badge issued to a specific identity.

If a second service adds another identity to the badge (say, a backpack), then the badge signature becomes invalid.
## Proposed solution to the problem created by the solution

When a secondary organization adds another identity to the assertion, they add a second signature, and clearly mark the ways they altered the original assertion. Multiple additions could be added this way, with a moderately complicated process of peeling each layer away and re-validating the badge. 

[Palimpsest?](http://en.wikipedia.org/wiki/Palimpsest)

**Comment by jeroenlicht** [comment]
Hi all,
I just signed up for GitHub to join this conversation since I figured this would be a problem when using openbadges for our project where we want to provide accreditation.
As a workaround, I am thinking of providing the possibility for users to re-create their earned badges from us after changing their email address in our system. 

Would it be a problem to distribute a new version of a badge with the same uid and issuedOn date? Or would it be better practice to give the re-issued badge a new uid and/or new issuedOn date?

For instance, when the badge (image) with the old email hash had already been distributed and added to badge displayers such as backpack, does adding the new one with the same uid maybe cause problems with badge-displaying systems?

**Comment by ottonomy** [comment]
As another approach, I'm fond of ways we might issue a badge that makes the claim "zzz@example.com" is another identifier for the person who is formerly known as "prince@aol.com". And then ways these tokens could be presented with a collection of other badges to let a consumer know that a trustworthy third party 

The credentials work moving forward at the w3c credentials community group has some interesting relevant approaches here. http://opencreds.org -- The idea being an identity document that can contain multiple credentials and information about multiple identifiers and additional metadata (name, address, etc) corresponding to that identity, paired with access control making sure to only release that to authorized parties.

**Comment by timothyfcook** [comment]
Moving to archive. Multiple identities now supported: https://github.com/openbadges/openbadges-specification/pull/99
